- hosts: all
  serial: 5
  gather_facts: no
  vars:
    username: 'kinshuk.bairagi'
  tasks:
  - name: Grant '{{username}}' sudo
    lineinfile:
      dest: /etc/sudoers.d/iaas
      state: present
      regexp: '^{{username}}'
      line: '{{username}} ALL=(ALL) NOPASSWD: ALL'
    become: true
